default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOSTNAME'] %>
  port: 5432

development:
  <<: *default
  database: start_dash_rails_vue_development

test:
  <<: *default
  database: start_dash_rails_vue_test

production:
  <<: *default
  database: start_dash_rails_vue_production
