version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/home/app/start-dash-rails-vue
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
    depends_on:
      - db
  # frontend:
  #   build:
  #     context: ./frontend
  #   command: ash -c "yarn start"
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3001:3000"
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,ses
      - DEFAULT_REGION=ap-northeast-1
