require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7

Rails/DynamicFindBy:
  Whitelist:
    - find_by_number

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Rails:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 2

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
